// Autogenerated using mud system-types
import { CatchSystem } from "./ethers-contracts/CatchSystem";
import { ComponentDevSystem } from "./ethers-contracts/ComponentDevSystem";
import { MoveSystem } from "./ethers-contracts/MoveSystem";
import { SetAuthorsSystem } from "./ethers-contracts/SetAuthorsSystem";
import { SetNameSystem } from "./ethers-contracts/SetNameSystem";
import { SetOwnerSystem } from "./ethers-contracts/SetOwnerSystem";
import { UploadSoundSystem } from "./ethers-contracts/UploadSoundSystem";
 
export type SystemTypes = {
  "system.Catch": CatchSystem;
  "mudwar.system.ComponentDev": ComponentDevSystem;
  "system.Move": MoveSystem;
  "system.SetAuthors": SetAuthorsSystem;
  "system.SetName": SetNameSystem;
  "system.SetOwner": SetOwnerSystem;
  "system.UploadSound": UploadSoundSystem;
};
