// Autogenerated using mud system-types
export const systemToId = {
  CatchSystem: "system.Catch",
  ComponentDevSystem: "mudwar.system.ComponentDev",
  MoveSystem: "system.Move",
  SetAuthorsSystem: "system.SetAuthors",
  SetNameSystem: "system.SetName",
  SetOwnerSystem: "system.SetOwner",
  UploadSoundSystem: "system.UploadSound",
};

export const idToSystem = {
  "system.Catch": "CatchSystem",
  "mudwar.system.ComponentDev": "ComponentDevSystem",
  "system.Move": "MoveSystem",
  "system.SetAuthors": "SetAuthorsSystem",
  "system.SetName": "SetNameSystem",
  "system.SetOwner": "SetOwnerSystem",
  "system.UploadSound": "UploadSoundSystem",
};
  