// Autogenerated using mud system-types
import CatchSystem from "../abi/CatchSystem.json";
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import SetAuthorsSystem from "../abi/SetAuthorsSystem.json";
import SetNameSystem from "../abi/SetNameSystem.json";
import SetOwnerSystem from "../abi/SetOwnerSystem.json";
import UploadSoundSystem from "../abi/UploadSoundSystem.json";

export const SystemAbis = {
  "system.Catch": CatchSystem.abi,
  "mudwar.system.ComponentDev": ComponentDevSystem.abi,
  "system.Move": MoveSystem.abi,
  "system.SetAuthors": SetAuthorsSystem.abi,
  "system.SetName": SetNameSystem.abi,
  "system.SetOwner": SetOwnerSystem.abi,
  "system.UploadSound": UploadSoundSystem.abi,
};
